alerting:
  discord:
    webhook-url: "${DISCORD_WEBHOOK_URL}"

endpoints:
  - name: front-end
    group: core
    url: "https://twin.sh/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: back-end
    group: core
    url: "https://example.org/"
    interval: 5m
    conditions:
      - "[STATUS] == 200"

  - name: monitoring
    group: internal
    url: "https://status.sammypulse.co.uk/health"
    interval: 5m
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: discord
        failure-threshold: 1
        send-on-resolved: true
